# Generated by Django 4.2.4 on 2023-08-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0006_alter_favproducts_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavProducts',
            new_name='Favourite',
        ),
    ]
